### ISSUE TITLE
[BUG] keepalived doesn't work correctly

### ISSUE THREAD

**Issue by zoumo** [caicloud/loadbalancer-provider#13]
**What is the issue about**:
keepalived VRRP LVS VIP

**What happened**:
Run loadbalancers on two ore more nodes in kubernetes.
VIP is now on node-1.
docker on node1 is crashed, and then kubelet not work correctly.
But VIP is still on node-1

**What you expected to happen**:
VIP should be shift to node-2 or other nodes

**Anything else we need to know**:

**Comment by kdada** [comment]
Keepalived can set health check for docker and kubelet.

**Comment by zoumo** [comment]
fixed
